# Generated by Django 5.2 on 2025-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_metaltype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
