# Generated by Django 5.2 on 2025-06-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_alter_country_options_country_flag_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='metaltype',
            options={'ordering': ['name'], 'verbose_name': 'Metal Type', 'verbose_name_plural': 'Metal Types'},
        ),
    ]
