# Generated by Django 5.2 on 2025-06-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0004_alter_country_options_alter_metaltype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transactions Types',
                'db_table': 'transactionstypes',
                'ordering': ['name'],
            },
        ),
    ]
