# Generated by Django 5.2 on 2025-06-27 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_content_type', models.CharField(blank=True, choices=[('photo', 'Fotografía'), ('video', 'Video'), ('documento', 'Archivo PDF'), ('text', 'Texto')], default='photo', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Digital Medium',
                'verbose_name_plural': 'Digital Media',
                'db_table': 'media_assets',
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_in_grams', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('gram', 'Gramo'), ('kilogram', 'Kilogramo'), ('onza', 'Onza'), ('ton', 'Tonelada')], default='gram', max_length=20)),
                ('purity', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('metal_form', models.CharField(choices=[('bar', 'Bar'), ('ingot', 'Lingote'), ('grain', 'Grano'), ('wire', 'Cable'), ('scrap', 'Chatarra'), ('rounded', 'Circular'), ('sheet', 'Lamina')], default='scrap', max_length=30)),
            ],
            options={
                'verbose_name': 'Metal',
                'verbose_name_plural': 'Metals',
                'db_table': 'metals',
            },
        ),
        migrations.CreateModel(
            name='CoinBankNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('coin_banknote', models.CharField(choices=[('coin', 'Moneda'), ('bank_note', 'Papel Moneda')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2025)])),
                ('denomination', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_country', to='reference_data.country')),
            ],
            options={
                'db_table': 'coinsbanknotes',
                'ordering': ['title'],
            },
        ),
    ]
