# Generated by Django 5.2 on 2025-06-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='metals',
            name='name',
        ),
        migrations.AddField(
            model_name='metal',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='metals',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='metal_form',
            field=models.CharField(choices=[('bar', 'Bar'), ('ingot', 'Lingote'), ('grain', 'Grano'), ('wire', 'Cable'), ('scrap', 'Chatarra'), ('rounded', 'Circular'), ('sheet', 'Lamina')], default='scrap', max_length=30),
        ),
        migrations.AlterField(
            model_name='metal',
            name='weight_unit',
            field=models.CharField(choices=[('gram', 'Gramo'), ('kilogram', 'Kilogramo'), ('onza', 'Onza'), ('ton', 'Tonelada')], default='gram', max_length=20),
        ),
    ]
