# Generated by Django 5.2 on 2025-06-27 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('reference_data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='content',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='metal',
            name='metal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.metaltype'),
        ),
    ]
