# Generated by Django 5.2 on 2025-06-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='title',
        ),
    ]
