# Generated by Django 5.2 on 2025-06-12 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_metal_name_remove_metals_name_metal_title_and_more'),
        ('reference_data', '0004_alter_country_options_alter_metaltype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBankNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('coin_banknote', models.CharField(choices=[('coin', 'Moneda'), ('bank_note', 'Papel Moneda')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2025)])),
                ('denomination', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_country', to='reference_data.country')),
            ],
            options={
                'db_table': 'coinsbanknotes',
                'ordering': ['title'],
            },
        ),
    ]
