# Generated by Django 5.2 on 2025-06-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_mediaasset_estimated_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='updated_at',
        ),
    ]
